2024-09-02 12:20:41,975 ERROR: Error occurred: 'list' object has no attribute 'items' [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-02 12:22:19,438 ERROR: Error occurred: No active exception to reraise [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-02 12:22:41,416 ERROR: Error occurred: No active exception to reraise [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-02 12:23:11,311 ERROR: Error occurred: No active exception to reraise [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-02 12:24:34,504 ERROR: Error occurred: No active exception to reraise [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-02 12:24:53,343 ERROR: Error occurred: No active exception to reraise [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-02 12:27:03,789 ERROR: Error occurred: 'Group' object has no attribute 'i' [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-02 12:34:47,515 ERROR: Error occurred: list indices must be integers or slices, not list [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-02 12:35:48,548 ERROR: Error occurred: list indices must be integers or slices, not list [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-02 12:36:15,425 ERROR: Error occurred: list indices must be integers or slices, not list [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-02 12:39:36,429 ERROR: Error occurred: list indices must be integers or slices, not list [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-02 12:42:17,630 ERROR: Error occurred: list indices must be integers or slices, not list [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-02 13:06:50,576 ERROR: Error occurred: 'int' object has no attribute 'session' [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-02 13:37:05,626 ERROR: Error occurred: local variable 'chat_id' referenced before assignment [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-04 12:50:40,227 ERROR: Error occurred: IN expression list, SELECT construct, or bound parameter object expected, got 1. [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-04 12:53:09,370 ERROR: Error occurred: 'dict' object has no attribute 'json' [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-04 13:16:49,582 ERROR: Error occurred: 'function' object is not subscriptable [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-04 13:17:31,479 ERROR: Error occurred: 'list' object has no attribute 'items' [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-04 13:19:31,080 ERROR: Error occurred: 'str' object has no attribute 'items' [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-04 13:22:00,071 ERROR: Error occurred: 'list' object has no attribute 'items' [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-04 13:22:11,547 ERROR: Error occurred: 'str' object has no attribute 'items' [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-04 13:22:57,520 ERROR: Error occurred: 'str' object has no attribute 'items' [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-04 13:23:54,233 ERROR: Error occurred: 'list' object has no attribute 'items' [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-04 13:35:10,201 ERROR: Error occurred: local variable 'formatted_message' referenced before assignment [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-04 13:36:40,316 ERROR: Error occurred: local variable 'i' referenced before assignment [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-04 13:50:18,926 ERROR: Error occurred: name 'con' is not defined [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-04 13:56:08,618 ERROR: Error occurred: list indices must be integers or slices, not dict [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-04 13:56:08,624 ERROR: Error occurred: list indices must be integers or slices, not dict [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-04 13:56:49,783 ERROR: Error occurred: list indices must be integers or slices, not dict [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-04 13:56:49,786 ERROR: Error occurred: list indices must be integers or slices, not dict [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-04 15:28:19,120 ERROR: Error occurred: local variable 'file_path' referenced before assignment [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-04 15:29:11,422 ERROR: Error occurred: File Not Found [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-04 15:29:24,619 ERROR: Error occurred: Unable to detect the MIME type because a file name is not available. Either set 'download_name', pass a path instead of a file, or set 'mimetype'. [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-04 15:30:07,936 ERROR: Error occurred: Unable to detect the MIME type because a file name is not available. Either set 'download_name', pass a path instead of a file, or set 'mimetype'. [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-04 15:30:37,423 ERROR: Error occurred: Unable to detect the MIME type because a file name is not available. Either set 'download_name', pass a path instead of a file, or set 'mimetype'. [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-04 15:32:14,587 ERROR: Error occurred: send_file() got an unexpected keyword argument 'attachment_filename' [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-04 15:32:30,021 ERROR: Error occurred: No name provided for attachment. Either set 'download_name' or pass a path instead of a file. [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-04 16:08:26,525 ERROR: Error occurred: bot token is not found [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-04 16:08:39,513 ERROR: Error occurred: bot token is not found [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-04 16:08:40,251 ERROR: Error occurred: bot token is not found [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-04 16:10:14,382 ERROR: Error occurred: group id is not found [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-04 16:10:21,433 ERROR: Error occurred: Group Not Found [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-04 16:10:23,272 ERROR: Error occurred: Group Not Found [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-04 16:10:35,431 ERROR: Error occurred: Group Not Found [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-04 16:10:54,202 ERROR: Error occurred: Group Not Found [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-04 16:11:55,833 ERROR: Error occurred: Group Not Found [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-04 16:13:42,877 ERROR: Error occurred: Group Not Found [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-04 16:14:05,653 ERROR: Error occurred: local variable 'group' referenced before assignment [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-04 16:14:25,361 ERROR: Error occurred: Group Not Found [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-04 16:14:42,615 ERROR: Error occurred: Group Not Found [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-05 10:39:50,459 ERROR: Error occurred: Object '<Settings at 0x7f9973760190>' is already attached to session '9' (this is '10') [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-05 11:18:39,338 ERROR: Error occurred: Invalid URL 'VwiJ294dhwij2919292ndunwdWnshfB992cW120WHkdsuccess_rate_channel.php': No scheme supplied. Perhaps you meant https://VwiJ294dhwij2919292ndunwdWnshfB992cW120WHkdsuccess_rate_channel.php? [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
2024-09-05 11:18:53,114 ERROR: Error occurred: Invalid URL 'VwiJ294dhwij2919292ndunwdWnshfB992cW120WHkdsuccess_rate_channel.php': No scheme supplied. Perhaps you meant https://VwiJ294dhwij2919292ndunwdWnshfB992cW120WHkdsuccess_rate_channel.php? [in /Users/adilanwar/Documents/tech_pay/tecpaybot/app/service/common/session_factory.py:71]
